-- barcode_seq (added in 20260626000009) started at 1, independent of barcodes already
-- generated by the old count-based fallback, so nextval() collided with existing rows.
-- Advance the sequence past the highest existing barcode suffix.
SELECT setval(
  'barcode_seq',
  GREATEST(
    (SELECT COALESCE(MAX(CAST(SUBSTRING(barcode FROM 8) AS BIGINT)), 0) FROM "ProductVariant"),
    (SELECT last_value FROM barcode_seq)
  ),
  true
);
