import { config } from 'dotenv'
config()

import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

function createClient() {
  const cs = (process.env.DATABASE_URL ?? '').replace(/&?channel_binding=[^&]*/g, '')
  const adapter = new PrismaPg({ connectionString: cs })
  return new PrismaClient({ adapter })
}

const prisma = createClient()

function slug(name: string) {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
}

function genBarcode(i: number) {
  const digits = '789' + String(i).padStart(9, '0')
  const check =
    (10 -
      (digits.split('').reduce((s, d, idx) => s + Number(d) * (idx % 2 === 0 ? 1 : 3), 0) % 10)) %
    10
  return digits + check
}

/* ── pools de imagens por categoria (12 fotos cada) ──── */
const IMG: Record<string, string[]> = {
  camisetas: [
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
    'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80',
    'https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=600&q=80',
    'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&q=80',
    'https://images.unsplash.com/photo-1503341733017-1901578f9f1e?w=600&q=80',
    'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80',
    'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600&q=80',
    'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&q=80',
    'https://images.unsplash.com/photo-1503342394128-c104d54dba01?w=600&q=80',
    'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
    'https://images.unsplash.com/photo-1555274175-6cbf6f3b137b?w=600&q=80',
    'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600&q=80',
  ],
  calcas: [
    'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80',
    'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=600&q=80',
    'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80',
    'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80',
    'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80',
    'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=600&q=80',
    'https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=600&q=80',
    'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80',
    'https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=600&q=80',
    'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80',
    'https://images.unsplash.com/photo-1613920153716-1e0f76b3f876?w=600&q=80',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
  ],
  calcados: [
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80',
    'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600&q=80',
    'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&q=80',
    'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80',
    'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
    'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&q=80',
    'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80',
    'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80',
    'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&q=80',
    'https://images.unsplash.com/photo-1556906781-9a412961a28d?w=600&q=80',
    'https://images.unsplash.com/photo-1579338559194-a162d19bf842?w=600&q=80',
  ],
  jaquetas: [
    'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=600&q=80',
    'https://images.unsplash.com/photo-1578681994506-b8f463449011?w=600&q=80',
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80',
    'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80',
    'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
    'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80',
    'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=600&q=80',
    'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=600&q=80',
    'https://images.unsplash.com/photo-1601762603339-fd61e28b698a?w=600&q=80',
    'https://images.unsplash.com/photo-1614975059251-992f11792b9f?w=600&q=80',
  ],
  acessorios: [
    'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80',
    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&q=80',
    'https://images.unsplash.com/photo-1523779105320-d1cd346ff52b?w=600&q=80',
    'https://images.unsplash.com/photo-1548369937-47519962c11a?w=600&q=80',
    'https://images.unsplash.com/photo-1591360236480-4ed4b4f3fd6e?w=600&q=80',
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
    'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&q=80',
    'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80',
    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
    'https://images.unsplash.com/photo-1627123424574-724758594785?w=600&q=80',
    'https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=600&q=80',
  ],
}

function imgs(cat: keyof typeof IMG, idx: number): string[] {
  const pool = IMG[cat]
  const n = pool.length
  return [pool[idx % n], pool[(idx + 1) % n], pool[(idx + 2) % n], pool[(idx + 3) % n]]
}

async function main() {
  console.log('🗑️  Deletando produtos existentes...')
  await prisma.orderItem.deleteMany()
  await prisma.product.deleteMany()
  console.log('  ✓ Produtos deletados\n')

  console.log('🌱 Criando categorias...')
  const catData = [
    { name: 'Camisetas', slug: 'camisetas' },
    { name: 'Calças', slug: 'calcas' },
    { name: 'Calçados', slug: 'calcados' },
    { name: 'Jaquetas', slug: 'jaquetas' },
    { name: 'Acessórios', slug: 'acessorios' },
  ]
  const cats: Record<string, string> = {}
  for (const c of catData) {
    const r = await prisma.category.upsert({ where: { slug: c.slug }, update: {}, create: c })
    cats[c.name] = r.id
  }
  console.log('  ✓ 5 categorias\n')

  console.log('🌱 Criando marcas...')
  const brandData = [
    { name: 'Nike', slug: 'nike' },
    { name: 'Adidas', slug: 'adidas' },
    { name: 'Puma', slug: 'puma' },
    { name: 'Under Armour', slug: 'under-armour' },
    { name: 'Mizuno', slug: 'mizuno' },
    { name: 'Balenciaga', slug: 'balenciaga' },
    { name: 'Boss', slug: 'boss' },
    { name: 'Reserva', slug: 'reserva' },
    { name: 'Hering', slug: 'hering' },
    { name: 'Dior', slug: 'dior' },
  ]
  const brands: Record<string, string> = {}
  for (const b of brandData) {
    const r = await prisma.brand.upsert({ where: { slug: b.slug }, update: {}, create: b })
    brands[b.name] = r.id
  }
  console.log('  ✓ 10 marcas\n')

  console.log('🌱 Criando tipos...')
  const typeData = [
    { name: 'Oversize', slug: 'oversize' },
    { name: 'Slim Fit', slug: 'slim-fit' },
    { name: 'Regular', slug: 'regular' },
    { name: 'Cropped', slug: 'cropped' },
    { name: 'Wide Leg', slug: 'wide-leg' },
    { name: 'Skinny', slug: 'skinny' },
  ]
  const types: Record<string, string> = {}
  for (const t of typeData) {
    const r = await prisma.productType.upsert({ where: { slug: t.slug }, update: {}, create: t })
    types[t.name] = r.id
  }
  console.log('  ✓ 6 tipos\n')

  type P = {
    name: string
    cat: string
    brand: string
    type: string
    price: number
    orig?: number
    stock: number
    featured: boolean
    imgKey: keyof typeof IMG
    imgIdx: number
  }

  const products: P[] = [
    // ── CAMISETAS (25) ──────────────────────────────────────────────────
    {
      name: 'Camiseta Oversize Essential Preta',
      cat: 'Camisetas',
      brand: 'Nike',
      type: 'Oversize',
      price: 129.9,
      orig: 179.9,
      stock: 45,
      featured: true,
      imgKey: 'camisetas',
      imgIdx: 0,
    },
    {
      name: 'Camiseta Slim Logo Branca',
      cat: 'Camisetas',
      brand: 'Adidas',
      type: 'Slim Fit',
      price: 99.9,
      orig: 139.9,
      stock: 30,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 1,
    },
    {
      name: 'Camiseta Regular Básica Cinza',
      cat: 'Camisetas',
      brand: 'Hering',
      type: 'Regular',
      price: 59.9,
      orig: undefined,
      stock: 80,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 2,
    },
    {
      name: 'Camiseta Cropped Tie-Dye Rosa',
      cat: 'Camisetas',
      brand: 'Puma',
      type: 'Cropped',
      price: 89.9,
      orig: 119.9,
      stock: 20,
      featured: true,
      imgKey: 'camisetas',
      imgIdx: 3,
    },
    {
      name: 'Camiseta Oversize Streetwear Azul',
      cat: 'Camisetas',
      brand: 'Reserva',
      type: 'Oversize',
      price: 149.9,
      orig: 199.9,
      stock: 15,
      featured: true,
      imgKey: 'camisetas',
      imgIdx: 4,
    },
    {
      name: 'Camiseta Slim Gola V Preta',
      cat: 'Camisetas',
      brand: 'Nike',
      type: 'Slim Fit',
      price: 109.9,
      orig: undefined,
      stock: 40,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 5,
    },
    {
      name: 'Camiseta Regular Estampada Floral',
      cat: 'Camisetas',
      brand: 'Reserva',
      type: 'Regular',
      price: 119.9,
      orig: 159.9,
      stock: 22,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 6,
    },
    {
      name: 'Camiseta Cropped Ribana Nude',
      cat: 'Camisetas',
      brand: 'Hering',
      type: 'Cropped',
      price: 79.9,
      orig: 109.9,
      stock: 35,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 7,
    },
    {
      name: 'Camiseta Manga Longa Off-White',
      cat: 'Camisetas',
      brand: 'Adidas',
      type: 'Regular',
      price: 139.9,
      orig: 179.9,
      stock: 28,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 8,
    },
    {
      name: 'Camiseta Oversize Logo Lateral Verde',
      cat: 'Camisetas',
      brand: 'Puma',
      type: 'Oversize',
      price: 119.9,
      orig: 149.9,
      stock: 18,
      featured: true,
      imgKey: 'camisetas',
      imgIdx: 9,
    },
    {
      name: 'Camiseta Dry-Fit Treino Laranja',
      cat: 'Camisetas',
      brand: 'Under Armour',
      type: 'Slim Fit',
      price: 149.9,
      orig: 199.9,
      stock: 50,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 10,
    },
    {
      name: 'Camiseta Polo Regular Branca',
      cat: 'Camisetas',
      brand: 'Reserva',
      type: 'Regular',
      price: 169.9,
      orig: 229.9,
      stock: 25,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 11,
    },
    {
      name: 'Camiseta Slim Listrada Marinho',
      cat: 'Camisetas',
      brand: 'Adidas',
      type: 'Slim Fit',
      price: 99.9,
      orig: undefined,
      stock: 38,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 0,
    },
    {
      name: 'Camiseta Regular Básica Vinho',
      cat: 'Camisetas',
      brand: 'Hering',
      type: 'Regular',
      price: 59.9,
      orig: undefined,
      stock: 60,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 1,
    },
    {
      name: 'Camiseta Oversize Drop Shoulder Cinza',
      cat: 'Camisetas',
      brand: 'Nike',
      type: 'Oversize',
      price: 159.9,
      orig: 209.9,
      stock: 20,
      featured: true,
      imgKey: 'camisetas',
      imgIdx: 2,
    },
    {
      name: 'Camiseta Manga Longa Gola Alta Preta',
      cat: 'Camisetas',
      brand: 'Mizuno',
      type: 'Slim Fit',
      price: 129.9,
      orig: 169.9,
      stock: 30,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 3,
    },
    {
      name: 'Camiseta Regular Bordada Bege',
      cat: 'Camisetas',
      brand: 'Boss',
      type: 'Regular',
      price: 199.9,
      orig: 269.9,
      stock: 12,
      featured: true,
      imgKey: 'camisetas',
      imgIdx: 4,
    },
    {
      name: 'Camiseta Oversize Tie-Dye Azul',
      cat: 'Camisetas',
      brand: 'Adidas',
      type: 'Oversize',
      price: 139.9,
      orig: 189.9,
      stock: 22,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 5,
    },
    {
      name: 'Camiseta Slim Muscle Fit Cinza',
      cat: 'Camisetas',
      brand: 'Under Armour',
      type: 'Slim Fit',
      price: 109.9,
      orig: undefined,
      stock: 45,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 6,
    },
    {
      name: 'Camiseta Regular Básica Branca',
      cat: 'Camisetas',
      brand: 'Hering',
      type: 'Regular',
      price: 49.9,
      orig: undefined,
      stock: 100,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 7,
    },
    {
      name: 'Camiseta Cropped Print Floral Coral',
      cat: 'Camisetas',
      brand: 'Puma',
      type: 'Cropped',
      price: 89.9,
      orig: 119.9,
      stock: 18,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 8,
    },
    {
      name: 'Camiseta Streetwear Print Logo Preta',
      cat: 'Camisetas',
      brand: 'Balenciaga',
      type: 'Oversize',
      price: 349.9,
      orig: 459.9,
      stock: 8,
      featured: true,
      imgKey: 'camisetas',
      imgIdx: 9,
    },
    {
      name: 'Camiseta Dry-Fit Compressão Esportiva',
      cat: 'Camisetas',
      brand: 'Mizuno',
      type: 'Slim Fit',
      price: 119.9,
      orig: 159.9,
      stock: 35,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 10,
    },
    {
      name: 'Camiseta Regular Algodão Premium Marrom',
      cat: 'Camisetas',
      brand: 'Dior',
      type: 'Regular',
      price: 499.9,
      orig: 649.9,
      stock: 5,
      featured: true,
      imgKey: 'camisetas',
      imgIdx: 11,
    },
    {
      name: 'Camiseta Cropped Vintage Rosa Claro',
      cat: 'Camisetas',
      brand: 'Hering',
      type: 'Cropped',
      price: 79.9,
      orig: 99.9,
      stock: 28,
      featured: false,
      imgKey: 'camisetas',
      imgIdx: 0,
    },

    // ── CALÇAS (20) ──────────────────────────────────────────────────────
    {
      name: 'Calça Slim Jeans Azul Escuro',
      cat: 'Calças',
      brand: 'Reserva',
      type: 'Slim Fit',
      price: 199.9,
      orig: 279.9,
      stock: 35,
      featured: true,
      imgKey: 'calcas',
      imgIdx: 0,
    },
    {
      name: 'Calça Regular Moletom Preta',
      cat: 'Calças',
      brand: 'Nike',
      type: 'Regular',
      price: 169.9,
      orig: 229.9,
      stock: 25,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 1,
    },
    {
      name: 'Calça Slim Chino Bege',
      cat: 'Calças',
      brand: 'Hering',
      type: 'Slim Fit',
      price: 179.9,
      orig: undefined,
      stock: 18,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 2,
    },
    {
      name: 'Calça Cargo Wide Leg Verde',
      cat: 'Calças',
      brand: 'Adidas',
      type: 'Wide Leg',
      price: 219.9,
      orig: 289.9,
      stock: 12,
      featured: true,
      imgKey: 'calcas',
      imgIdx: 3,
    },
    {
      name: 'Calça Jogger Slim Preta',
      cat: 'Calças',
      brand: 'Puma',
      type: 'Slim Fit',
      price: 189.9,
      orig: 249.9,
      stock: 22,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 4,
    },
    {
      name: 'Calça Jeans Wide Leg Azul Claro',
      cat: 'Calças',
      brand: 'Reserva',
      type: 'Wide Leg',
      price: 229.9,
      orig: 299.9,
      stock: 15,
      featured: true,
      imgKey: 'calcas',
      imgIdx: 5,
    },
    {
      name: 'Calça Legging Compressão Preta',
      cat: 'Calças',
      brand: 'Under Armour',
      type: 'Skinny',
      price: 149.9,
      orig: 199.9,
      stock: 40,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 6,
    },
    {
      name: 'Calça Slim Alfaiataria Cinza',
      cat: 'Calças',
      brand: 'Boss',
      type: 'Slim Fit',
      price: 349.9,
      orig: 459.9,
      stock: 10,
      featured: true,
      imgKey: 'calcas',
      imgIdx: 7,
    },
    {
      name: 'Calça Cargo Relaxed Cáqui',
      cat: 'Calças',
      brand: 'Adidas',
      type: 'Regular',
      price: 209.9,
      orig: 269.9,
      stock: 20,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 8,
    },
    {
      name: 'Calça Regular Linho Bege',
      cat: 'Calças',
      brand: 'Reserva',
      type: 'Regular',
      price: 239.9,
      orig: undefined,
      stock: 14,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 9,
    },
    {
      name: 'Calça Skinny Jeans Preta',
      cat: 'Calças',
      brand: 'Puma',
      type: 'Skinny',
      price: 179.9,
      orig: 229.9,
      stock: 28,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 10,
    },
    {
      name: 'Calça Moletom Slim Cinza Mescla',
      cat: 'Calças',
      brand: 'Nike',
      type: 'Slim Fit',
      price: 159.9,
      orig: 199.9,
      stock: 32,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 11,
    },
    {
      name: 'Calça Jeans Regular Destroyed Azul',
      cat: 'Calças',
      brand: 'Adidas',
      type: 'Regular',
      price: 199.9,
      orig: 259.9,
      stock: 16,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 0,
    },
    {
      name: 'Calça Slim Sarja Verde Musgo',
      cat: 'Calças',
      brand: 'Hering',
      type: 'Slim Fit',
      price: 189.9,
      orig: undefined,
      stock: 22,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 1,
    },
    {
      name: 'Calça Wide Leg Linho Off-White',
      cat: 'Calças',
      brand: 'Reserva',
      type: 'Wide Leg',
      price: 259.9,
      orig: 329.9,
      stock: 10,
      featured: true,
      imgKey: 'calcas',
      imgIdx: 2,
    },
    {
      name: 'Calça Jogger Refletivo Preta',
      cat: 'Calças',
      brand: 'Mizuno',
      type: 'Slim Fit',
      price: 199.9,
      orig: 259.9,
      stock: 18,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 3,
    },
    {
      name: 'Calça Slim Colorida Marsala',
      cat: 'Calças',
      brand: 'Hering',
      type: 'Slim Fit',
      price: 149.9,
      orig: undefined,
      stock: 20,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 4,
    },
    {
      name: 'Calça Jeans High Waist Azul',
      cat: 'Calças',
      brand: 'Adidas',
      type: 'Skinny',
      price: 219.9,
      orig: 289.9,
      stock: 15,
      featured: true,
      imgKey: 'calcas',
      imgIdx: 5,
    },
    {
      name: 'Calça Cargo Multi-Pocket Preta',
      cat: 'Calças',
      brand: 'Under Armour',
      type: 'Regular',
      price: 229.9,
      orig: 299.9,
      stock: 12,
      featured: false,
      imgKey: 'calcas',
      imgIdx: 6,
    },
    {
      name: 'Calça Slim Denim Premium Indigo',
      cat: 'Calças',
      brand: 'Boss',
      type: 'Slim Fit',
      price: 399.9,
      orig: 519.9,
      stock: 8,
      featured: true,
      imgKey: 'calcas',
      imgIdx: 7,
    },

    // ── CALÇADOS (20) ────────────────────────────────────────────────────
    {
      name: 'Tênis Running Air Max Branco',
      cat: 'Calçados',
      brand: 'Nike',
      type: 'Regular',
      price: 399.9,
      orig: 529.9,
      stock: 22,
      featured: true,
      imgKey: 'calcados',
      imgIdx: 0,
    },
    {
      name: 'Tênis Ultraboost Preto',
      cat: 'Calçados',
      brand: 'Adidas',
      type: 'Regular',
      price: 449.9,
      orig: 599.9,
      stock: 18,
      featured: true,
      imgKey: 'calcados',
      imgIdx: 1,
    },
    {
      name: 'Tênis Lifestyle Suede Vermelho',
      cat: 'Calçados',
      brand: 'Puma',
      type: 'Regular',
      price: 299.9,
      orig: 399.9,
      stock: 14,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 2,
    },
    {
      name: 'Chinelo Slide Recovery Preto',
      cat: 'Calçados',
      brand: 'Nike',
      type: 'Regular',
      price: 129.9,
      orig: 169.9,
      stock: 40,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 3,
    },
    {
      name: 'Tênis Training Cross Preta',
      cat: 'Calçados',
      brand: 'Under Armour',
      type: 'Regular',
      price: 349.9,
      orig: 459.9,
      stock: 20,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 4,
    },
    {
      name: 'Tênis Casual Court Branco',
      cat: 'Calçados',
      brand: 'Adidas',
      type: 'Regular',
      price: 279.9,
      orig: 359.9,
      stock: 25,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 5,
    },
    {
      name: 'Tênis Slip-On Lifestyle Preto',
      cat: 'Calçados',
      brand: 'Puma',
      type: 'Regular',
      price: 199.9,
      orig: 259.9,
      stock: 30,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 6,
    },
    {
      name: 'Tênis Trail Running Verde',
      cat: 'Calçados',
      brand: 'Nike',
      type: 'Regular',
      price: 429.9,
      orig: 559.9,
      stock: 16,
      featured: true,
      imgKey: 'calcados',
      imgIdx: 7,
    },
    {
      name: 'Tênis Retro Colorblock',
      cat: 'Calçados',
      brand: 'Adidas',
      type: 'Regular',
      price: 319.9,
      orig: 419.9,
      stock: 14,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 8,
    },
    {
      name: 'Tênis Dad Shoe Chunky Branco',
      cat: 'Calçados',
      brand: 'Balenciaga',
      type: 'Regular',
      price: 2499.9,
      orig: undefined,
      stock: 4,
      featured: true,
      imgKey: 'calcados',
      imgIdx: 9,
    },
    {
      name: 'Bota Coturno Couro Preto',
      cat: 'Calçados',
      brand: 'Hering',
      type: 'Regular',
      price: 349.9,
      orig: 459.9,
      stock: 12,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 10,
    },
    {
      name: 'Sapatênis Casual Marrom',
      cat: 'Calçados',
      brand: 'Reserva',
      type: 'Regular',
      price: 249.9,
      orig: 319.9,
      stock: 18,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 11,
    },
    {
      name: 'Tênis Treino Indoor Azul',
      cat: 'Calçados',
      brand: 'Mizuno',
      type: 'Regular',
      price: 299.9,
      orig: 389.9,
      stock: 22,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 0,
    },
    {
      name: 'Tênis Lifestyle Velcro Branco',
      cat: 'Calçados',
      brand: 'Puma',
      type: 'Regular',
      price: 249.9,
      orig: 319.9,
      stock: 16,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 1,
    },
    {
      name: 'Bota Ankle Boot Preta',
      cat: 'Calçados',
      brand: 'Hering',
      type: 'Regular',
      price: 299.9,
      orig: 399.9,
      stock: 10,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 2,
    },
    {
      name: 'Tênis Running React Cinza',
      cat: 'Calçados',
      brand: 'Nike',
      type: 'Regular',
      price: 479.9,
      orig: 629.9,
      stock: 14,
      featured: true,
      imgKey: 'calcados',
      imgIdx: 3,
    },
    {
      name: 'Tênis Low Casual Off-White',
      cat: 'Calçados',
      brand: 'Adidas',
      type: 'Regular',
      price: 269.9,
      orig: 349.9,
      stock: 20,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 4,
    },
    {
      name: 'Sandália Esportiva Preta',
      cat: 'Calçados',
      brand: 'Puma',
      type: 'Regular',
      price: 149.9,
      orig: 199.9,
      stock: 28,
      featured: false,
      imgKey: 'calcados',
      imgIdx: 5,
    },
    {
      name: 'Tênis Mid Cano Alto Branco',
      cat: 'Calçados',
      brand: 'Nike',
      type: 'Regular',
      price: 419.9,
      orig: 549.9,
      stock: 12,
      featured: true,
      imgKey: 'calcados',
      imgIdx: 6,
    },
    {
      name: 'Loafer Mocassim Couro Nude',
      cat: 'Calçados',
      brand: 'Boss',
      type: 'Regular',
      price: 599.9,
      orig: 779.9,
      stock: 8,
      featured: true,
      imgKey: 'calcados',
      imgIdx: 7,
    },

    // ── JAQUETAS (20) ────────────────────────────────────────────────────
    {
      name: 'Jaqueta Corta-Vento Running Preta',
      cat: 'Jaquetas',
      brand: 'Nike',
      type: 'Regular',
      price: 299.9,
      orig: 399.9,
      stock: 20,
      featured: true,
      imgKey: 'jaquetas',
      imgIdx: 0,
    },
    {
      name: 'Jaqueta Bomber Oversized Bege',
      cat: 'Jaquetas',
      brand: 'Reserva',
      type: 'Oversize',
      price: 349.9,
      orig: 459.9,
      stock: 10,
      featured: true,
      imgKey: 'jaquetas',
      imgIdx: 1,
    },
    {
      name: 'Jaqueta Jeans Slim Azul',
      cat: 'Jaquetas',
      brand: 'Hering',
      type: 'Slim Fit',
      price: 259.9,
      orig: 339.9,
      stock: 15,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 2,
    },
    {
      name: 'Moletom Canguru Cropped Lilás',
      cat: 'Jaquetas',
      brand: 'Puma',
      type: 'Cropped',
      price: 189.9,
      orig: 249.9,
      stock: 25,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 3,
    },
    {
      name: 'Jaqueta Couro Sintético Premium Preta',
      cat: 'Jaquetas',
      brand: 'Adidas',
      type: 'Slim Fit',
      price: 399.9,
      orig: 529.9,
      stock: 8,
      featured: true,
      imgKey: 'jaquetas',
      imgIdx: 4,
    },
    {
      name: 'Moletom Oversize Logo Cinza',
      cat: 'Jaquetas',
      brand: 'Nike',
      type: 'Oversize',
      price: 219.9,
      orig: 289.9,
      stock: 30,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 5,
    },
    {
      name: 'Jaqueta Técnica Impermeável Azul',
      cat: 'Jaquetas',
      brand: 'Under Armour',
      type: 'Regular',
      price: 449.9,
      orig: 589.9,
      stock: 12,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 6,
    },
    {
      name: 'Jaqueta Sherpa Forrada Caramelo',
      cat: 'Jaquetas',
      brand: 'Reserva',
      type: 'Regular',
      price: 379.9,
      orig: 499.9,
      stock: 10,
      featured: true,
      imgKey: 'jaquetas',
      imgIdx: 7,
    },
    {
      name: 'Moletom Regular Estampado Branco',
      cat: 'Jaquetas',
      brand: 'Puma',
      type: 'Regular',
      price: 199.9,
      orig: 259.9,
      stock: 22,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 8,
    },
    {
      name: 'Jaqueta Windbreaker Colorblock',
      cat: 'Jaquetas',
      brand: 'Nike',
      type: 'Regular',
      price: 329.9,
      orig: 429.9,
      stock: 14,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 9,
    },
    {
      name: 'Jaqueta Puffer Leve Preta',
      cat: 'Jaquetas',
      brand: 'Adidas',
      type: 'Regular',
      price: 359.9,
      orig: 469.9,
      stock: 12,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 10,
    },
    {
      name: 'Moletom Aberto Slim Verde',
      cat: 'Jaquetas',
      brand: 'Hering',
      type: 'Slim Fit',
      price: 169.9,
      orig: undefined,
      stock: 28,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 11,
    },
    {
      name: 'Jaqueta Sarja Oversize Areia',
      cat: 'Jaquetas',
      brand: 'Reserva',
      type: 'Oversize',
      price: 299.9,
      orig: 389.9,
      stock: 10,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 0,
    },
    {
      name: 'Moletom Canguru Regular Bordô',
      cat: 'Jaquetas',
      brand: 'Puma',
      type: 'Regular',
      price: 179.9,
      orig: 229.9,
      stock: 20,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 1,
    },
    {
      name: 'Jaqueta Corta-Vento Refletivo Cinza',
      cat: 'Jaquetas',
      brand: 'Mizuno',
      type: 'Regular',
      price: 279.9,
      orig: 359.9,
      stock: 16,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 2,
    },
    {
      name: 'Blazer Slim Premium Preto',
      cat: 'Jaquetas',
      brand: 'Boss',
      type: 'Slim Fit',
      price: 699.9,
      orig: 899.9,
      stock: 6,
      featured: true,
      imgKey: 'jaquetas',
      imgIdx: 3,
    },
    {
      name: 'Moletom Cropped Tie-Dye Rosa',
      cat: 'Jaquetas',
      brand: 'Reserva',
      type: 'Cropped',
      price: 189.9,
      orig: 249.9,
      stock: 18,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 4,
    },
    {
      name: 'Jaqueta Puffer Colorida Oversized',
      cat: 'Jaquetas',
      brand: 'Balenciaga',
      type: 'Oversize',
      price: 1999.9,
      orig: undefined,
      stock: 3,
      featured: true,
      imgKey: 'jaquetas',
      imgIdx: 5,
    },
    {
      name: 'Jaqueta Jeans Oversize Desgastada',
      cat: 'Jaquetas',
      brand: 'Hering',
      type: 'Oversize',
      price: 229.9,
      orig: 299.9,
      stock: 14,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 6,
    },
    {
      name: 'Moletom Slim Básico Off-White',
      cat: 'Jaquetas',
      brand: 'Adidas',
      type: 'Slim Fit',
      price: 179.9,
      orig: 229.9,
      stock: 35,
      featured: false,
      imgKey: 'jaquetas',
      imgIdx: 7,
    },

    // ── ACESSÓRIOS (15) ──────────────────────────────────────────────────
    {
      name: 'Boné Aba Curva Dad Hat Preto',
      cat: 'Acessórios',
      brand: 'Nike',
      type: 'Regular',
      price: 89.9,
      orig: 119.9,
      stock: 50,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 0,
    },
    {
      name: 'Mochila Esportiva 30L Preta',
      cat: 'Acessórios',
      brand: 'Adidas',
      type: 'Regular',
      price: 199.9,
      orig: 259.9,
      stock: 18,
      featured: true,
      imgKey: 'acessorios',
      imgIdx: 1,
    },
    {
      name: 'Meia Cano Médio Pack 3 Pares',
      cat: 'Acessórios',
      brand: 'Hering',
      type: 'Regular',
      price: 39.9,
      orig: undefined,
      stock: 100,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 2,
    },
    {
      name: 'Carteira Slim Couro Preta',
      cat: 'Acessórios',
      brand: 'Reserva',
      type: 'Regular',
      price: 149.9,
      orig: 199.9,
      stock: 25,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 3,
    },
    {
      name: 'Óculos de Sol Esportivo Preto',
      cat: 'Acessórios',
      brand: 'Puma',
      type: 'Regular',
      price: 129.9,
      orig: 169.9,
      stock: 30,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 4,
    },
    {
      name: 'Cinto Trançado Couro Marrom',
      cat: 'Acessórios',
      brand: 'Boss',
      type: 'Regular',
      price: 199.9,
      orig: 259.9,
      stock: 20,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 5,
    },
    {
      name: 'Boné Trucker Snapback Preto',
      cat: 'Acessórios',
      brand: 'Adidas',
      type: 'Regular',
      price: 79.9,
      orig: 99.9,
      stock: 40,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 6,
    },
    {
      name: 'Touca Beanie Cinza Mescla',
      cat: 'Acessórios',
      brand: 'Puma',
      type: 'Regular',
      price: 59.9,
      orig: 79.9,
      stock: 35,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 7,
    },
    {
      name: 'Pochete Crossbody Preta',
      cat: 'Acessórios',
      brand: 'Nike',
      type: 'Regular',
      price: 119.9,
      orig: 159.9,
      stock: 22,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 8,
    },
    {
      name: 'Relógio Digital Sport Preta',
      cat: 'Acessórios',
      brand: 'Mizuno',
      type: 'Regular',
      price: 299.9,
      orig: 399.9,
      stock: 15,
      featured: true,
      imgKey: 'acessorios',
      imgIdx: 9,
    },
    {
      name: 'Óculos Retro Redondo Dourado',
      cat: 'Acessórios',
      brand: 'Dior',
      type: 'Regular',
      price: 499.9,
      orig: 649.9,
      stock: 8,
      featured: true,
      imgKey: 'acessorios',
      imgIdx: 10,
    },
    {
      name: 'Bolsa Tote Canvas Bege',
      cat: 'Acessórios',
      brand: 'Hering',
      type: 'Regular',
      price: 99.9,
      orig: 129.9,
      stock: 20,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 11,
    },
    {
      name: 'Necessaire Sport Impermeável Preta',
      cat: 'Acessórios',
      brand: 'Nike',
      type: 'Regular',
      price: 79.9,
      orig: 99.9,
      stock: 30,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 0,
    },
    {
      name: 'Pulseira Elástica Sport Preta',
      cat: 'Acessórios',
      brand: 'Under Armour',
      type: 'Regular',
      price: 49.9,
      orig: undefined,
      stock: 50,
      featured: false,
      imgKey: 'acessorios',
      imgIdx: 1,
    },
    {
      name: 'Boné Dad Hat Premium Bege',
      cat: 'Acessórios',
      brand: 'Balenciaga',
      type: 'Regular',
      price: 899.9,
      orig: 1199.9,
      stock: 4,
      featured: true,
      imgKey: 'acessorios',
      imgIdx: 2,
    },
  ]

  console.log('🌱 Criando 100 produtos...\n')
  let created = 0

  for (let i = 0; i < products.length; i++) {
    const p = products[i]
    const productSlug = slug(p.name) + '-' + (i + 1)
    const images = imgs(p.imgKey, p.imgIdx)

    try {
      await prisma.product.create({
        data: {
          name: p.name,
          slug: productSlug,
          description: `${p.name} — estilo ${p.type} da marca ${p.brand}. Produto de alta qualidade com conforto superior e design exclusivo. Ideal para o dia a dia e ocasiões especiais. Material premium com acabamento impecável.`,
          price: p.price,
          originalPrice: p.orig ?? null,
          costPrice: Math.round(p.price * 0.4 * 100) / 100,
          marginPercent: 150,
          images,
          categoryId: cats[p.cat],
          brandId: brands[p.brand],
          typeId: types[p.type],
          stock: p.stock,
          isActive: true,
          isFeatured: p.featured,
          barcode: genBarcode(i + 1),
        },
      })
      created++
      process.stdout.write(`  ✓ ${created}/100 — ${p.name}\n`)
    } catch (e) {
      console.error(`  ✗ Erro em "${p.name}":`, (e as Error).message)
    }

    await new Promise((r) => setTimeout(r, 15))
  }

  console.log(`\n✅ Seed concluído! ${created}/100 produtos criados.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
